defmodule Pixelgame.NameGenerator do
  @adjectives {
    "alleged",
    "american",
    "bad",
    "bargain",
    "bossy",
    "budget",
    "captain",
    "colluding",
    "conniving",
    "cheeky",
    "corrupt",
    "crooked",
    "default",
    "dirty",
    "dodgy",
    "enraged",
    "european",
    "evil",
    "faithless",
    "fishy",
    "flirty",
    "foolish",
    "fraudulent",
    "freaky",
    "general",
    "grumpy",
    "gym",
    "horse",
    "illegal",
    "illicit",
    "immoral",
    "impetuous",
    "large",
    "lil",
    "legitimate",
    "level one",
    "level 100",
    "lying",
    "mean",
    "prodigal",
    "raging",
    "secret",
    "shady",
    "sigma",
    "silly",
    "sleepy",
    "smug",
    "street",
    "super",
    "sus",
    "stealthy"
  }
  @nouns {
    "american",
    "baddie",
    "boss",
    "bozo",
    "bro",
    "bystander",
    "child",
    "clown",
    "cow",
    "coward",
    "crook",
    "doorknob",
    "european",
    "fiend",
    "fool",
    "friend",
    "gamer",
    "girl",
    "guy",
    "hero",
    "homeowner",
    "imposter",
    "knave",
    "joe",
    "goofball",
    "jockey",
    "meanie",
    "monarch",
    "oligarch",
    "pirate",
    "rascal",
    "sapling",
    "scallywag",
    "schmoe",
    "scoundrel",
    "scum",
    "seaman",
    "sinner",
    "snack",
    "villain",
    "youngin",
    "youngster"
  }

  @adjectives_size tuple_size(@adjectives)
  @nouns_size tuple_size(@nouns)

  @doc """
  This generates an adjective noun string with > 1000 total possibilities
  """
  def generate_name() do
    adj = elem(@adjectives, :rand.uniform(@adjectives_size) - 1)
    noun = elem(@nouns, :rand.uniform(@nouns_size) - 1)
    adj <> " " <> noun
  end
end
